# Generated by Django 4.2 on 2024-11-01 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Technician_activities', '0002_action_pattern_ticketinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketinfo',
            name='ticket_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_infos', to='Technician_activities.ticket'),
        ),
    ]
